name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

  secrets: inherit
jobs:
  job1:
    uses: ManthanThakkar1/ReusableWorkflow/.github/workflows/main.yaml@main
    secrets:
      test: ${{ secrets.test }}